created user entity, implemented simple registration
volodymyrruso/book-store pull request #6
Opened 2024-05-16 10:14 UTC by volodymyrruso

2024-05-21 14:59 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2024-05-21 14:59 UTC, liliia-ponomarenko commented on src/main/java/org/mate/bookstorespringboot/controller/dto/UserRequestDto.java
> +
```suggestion
```
redundant empty lines

2024-05-21 14:59 UTC, liliia-ponomarenko commented on src/main/java/org/mate/bookstorespringboot/controller/AuthenticationController.java
> +    public ResponseEntity<UserResponseDto> register(
We already  discussed  about wrapping  to response entity ;)

2024-05-21 14:59 UTC, liliia-ponomarenko commented on src/main/java/org/mate/bookstorespringboot/exceptions/RegistrationException.java
> +
```suggestion
```

2024-05-21 14:59 UTC, liliia-ponomarenko commented on src/main/java/org/mate/bookstorespringboot/exceptions/RegistrationException.java
> +    }
do you really need both constructors?

2024-05-21 14:59 UTC, liliia-ponomarenko commented on src/main/java/org/mate/bookstorespringboot/validation/annotations/FieldMatch.java
> +
```suggestion
```
empty lines

2024-05-21 14:59 UTC, liliia-ponomarenko commented on src/main/java/org/mate/bookstorespringboot/validation/annotations/ValidPassword.java
> +
```suggestion
import org.mate.bookstorespringboot.validation.impl.PasswordConstraintValidator;
```

2024-05-21 14:59 UTC, liliia-ponomarenko commented on src/main/java/org/mate/bookstorespringboot/validation/impl/EmailConstraintValidator.java
> +        }
Why do you return true if email is `null`? Can email be a `null` value?

2024-05-21 14:59 UTC, liliia-ponomarenko commented on src/main/java/org/mate/bookstorespringboot/validation/impl/PasswordConstraintValidator.java
> +            if (AT_LEAST_ONE_DIGIT.matcher(password).matches()) {
solution with count looks strange. Can you return false if some conditional is not met?

2024-05-21 14:59 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +            path: db/changelog/changeset_create_table/create_user_table.sql
add one empty line ;)

2024-05-21 14:59 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changeset_create_table/create_user_table.sql
> +                    last_name VARCHAR(50) NOT NULL,
you should have the same size requirements for your request DTO ;)

2024-05-27 08:41 UTC, volodymyrruso commented on src/main/resources/db/changelog/changeset_create_table/create_user_table.sql
> +                    last_name VARCHAR(50) NOT NULL,
password i did this way because I'll be hashing the password so the size will be different than for the request, with first and last name I agree

2024-05-28 08:31 UTC, liliia-ponomarenko approved these changes
great 😊

2024-06-26 13:57 UTC, merged